title = "Sreenivas"
paginate = 5

[params]
dateFormat = "Jan 2, 2006, 3:04PM"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20
